exclude: [
    'config.yml',
    'vendor', # CircleCI-specific bug
    'Gemfile*',
    '*.sh',
    'README.md',

]
highlighter: rouge
permalink: /:title/
name: Turing Mechanic
url: 'https://www.TuringMechanic.com'
author: Philip I. Thomas
author_url: https://www.philipithomas.com
description: Algorithms in GoLang
twitter: TuringMechanic
github: https://github.com/philipithomas/TuringMechanic/tree/master
copyright: All rights reserved
rss_path: /
rss_name: rss.xml
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  debug: true
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images

gems:
  - jekyll-sitemap


code-base: "https://github.com/philipithomas/TuringMechanic/tree/master/go/src/"

favicon: 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDo5MTlGMEU3RDYzREQxMUU0OERCQkU5NzZBMzhEQ0I1NSIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo5MTlGMEU3RTYzREQxMUU0OERCQkU5NzZBMzhEQ0I1NSI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOjkxOUYwRTdCNjNERDExRTQ4REJCRTk3NkEzOERDQjU1IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOjkxOUYwRTdDNjNERDExRTQ4REJCRTk3NkEzOERDQjU1Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+zvbqWQAAAkNJREFUeNpkUktMk0EQ3tnd/1UqlrdYLAIG68FGLYT44KRcjF70wsGzURNNPBOPeiDxxEWv4LnRxMRoQDhwEIHECGpFxWCJQKFEai1t998d//0rj+Aku9mdnW9mvm8WWh79IdpAb4iSGUVm8MwyoCLVB0BJhkqf9Tt6i5Mdg5LhBNdTV2YG47Hawv7Q28RLAD56sV8Yjsb4xsu5wYtmVvjbcN/C0PH0h5bBqdHJieDQNObIsJIEqFe8DKB+NBZNO/zxxZPuzYa7txIla/xhf+vaate+UDfLty+Ml7ix3YYGCO40zb2+8fxmJZBDkVbaeeJNanJl4L61mg4wuPw5ISQSgB2ALoHSdIL5B/ey16+dT7473XHBCNQghU1u9yxPxOaeEfZPGFZ1qY8pkWmILtZEryYTVi4XyJfsqemK3AZ4WV1VAViH87ORzl9QR4mivlpgi+Kn5rNj9acckJIzC5AhZiucpSNhCiSbdr/KJg5yqyV/AtSwB+J3fhKTE6UVASgJF0uuAHoQC7ZbKNOg2/RNUZhvPjdS32G5Re+qgNQKN5xKUwocwKuDO6TLNTxCjLyvjqLSpQG1RzFKEX9TSzAT/FFQsnvUhMhAFe7yePS4EuvBEJo2+R9QVpij67WLmgUJqsKSyxejxyIyJYHv+UvEkCrZdHJmprG9kLFAbiAdCR19HL8929YTUEWGQmfc/Vu9lWdO19qr3szTsZXDycbYl8gZcCo9PfwYtRfg+1it+EEYfLfbHCSmp5hSW4+aw18BBgANVPSRivb6kwAAAABJRU5ErkJggg==' # TODO - base64 encode
