exclude: [
    'config.yml',
    'vendor', # CircleCI-specific bug
    'Gemfile*',
    '*.sh',
    'README.md',

]

highlighter: pygment
permalink: /:title/
name: Turing Mechanic
url: 'https://www.TuringMechanic.com'
author: Philip I. Thomas
author_url: https://www.philipithomas.com
description: Algorithms in GoLang
twitter: TuringMechanic
github: https://github.com/philipithomas/TuringMechanic/tree/master
copyright: All rights reserved
rss_path: /
rss_name: rss.xml
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  debug: true
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images

favicon: '' # TODO - base64 encode
code-base: https:/github.com/philipithomas/TuringMachine/tree/master/go/
